version: "3.7"

services:
  road2:
    build:
      context: ../..
      dockerfile: ./docker/demonstration/Dockerfile
    image: road2
    container_name: road2-server
    depends_on:
      - pgrouting
    environment:
      - NODE_ENV=debug
    command : "npm run debug -- --ROAD2_CONF_FILE=../config/road2.json"
    ports:
      - 8080:8080
      - 9229:9229
      - 9230:9230
      - 443:443
    volumes:
      - iti-data-volume:/home/docker/data
      - ${road2_src}:/home/docker/app/src
      - ${road2_test}:/home/docker/app/test
      - ${road2_config}:/home/docker/config
    networks:
      - iti-network
    secrets:
      - key
      - cert

  r2gg:
    build:
      context: ../route-graph-generator/
      dockerfile: ./docker/debian/Dockerfile
    image: r2gg
    container_name: r2gg
    depends_on:
      - pgrouting
    volumes:
      - iti-data-volume:/home/docker/data
      - ${r2gg_src}:/usr/lib/python3.6/site-packages/r2gg/r2gg
    networks:
      - iti-network
    command: "./r2gg_pipeline.sh"
    environment:
      - R2GG_ARG=${R2GG_ARG}
      - GENERATION_TYPE=${GENERATION_TYPE}
    secrets:
      - db_config

  pgrouting:
    build:
      context: ../motors/pgrouting-procedures/
      dockerfile: ./docker/debian/Dockerfile
    image: pgrouting
    container_name: pgrouting-server
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - iti-network
    volumes:
      - pgr-data-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  iti-data-volume:
    name: iti-data-volume
  pgr-data-volume:
    name: pgr-data-volume

networks:
  iti-network:
    # Nom utilisé ailleurs dans ce projet
    name: iti-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${iprange}

secrets:
  db_config:
    file: ${db_config_file}
  key:
    file: ${road2_key}
  cert:
    file: ${road2_cert}
