application:
	name: "Road2"
	title: "Service d'itinéraire du Géoportail"
	description: "Ce service permet de calculer des itinéraires sur les données du Géoportail."
  url: "https://wxs.ign.fr/#KEY/geoportail/itineraire"
  provider:
		name: "IGN"
		site: "https://www.ign.fr"
		mail: "idev@ign.fr"
	logs:
		configuration: "configuration_logs.yaml"
  operations:
    directory: "/home/src/resources/operations/"
    parameters:
      directory: "/home/src/resources/parameters/"
	resources:
		directories:
      - "/home/config/resources/"
  network:
    host: "0.0.0.0"
    port: "8080"
