application:
	name: "Road4"
	title: "Service d'itinéraire du Géoportail"
	description: "Ce service permet de calculer des itinéraires sur les données du Géoportail."
	provider:
		name: "IGN"
		site: "https://www.ign.fr"
		mail: "idev@ign.fr"
	logs:
		configuration: "configuration_logs.yaml"
	resources:
		directory: "/directory/"
  network:
    host: "0.0.0.0"
    port: "8080"
