# Description d'un fichier de configuration de l'application Road4

# Une application est un objet qui contient toutes les informations utiles pour que l'application puisse diffuser ses services.
"application":
	type: object
	required: true
	properties:
		# Nom de l'application qui va apparaître dans le getcap
		"name":
			type: string
			required: true
		# Titre qui va apparaître dans le getcap
		"title":
			type: string
			required: true
		# Description qui va apparaître dans le getcap
		"description":
			type: string
			required: true
    # Url du service qui va apparaître dans le getcap
    "url":
      type: string
      required: true
		# Information sur le fournisseur du service
		"provider":
			type: object
			required: false
			properties:
				# Nom du fournisseur
				"name":
					type: string
					required: true
				# Site web du fournisseur
				"site":
					type: string
					required: false
				# Adresse mail du fournisseur
				"mail":
					type: string
					required: true
		# Configuration des logs de l'application
		"logs":
			type: object
			required: true
			properties:
				# Emplacement du fichier de configuration
				"configuration":
					type: string
					required: true
    # Configuration des opérations autorisées dans le service
    "operations":
      type: object
      required: true
      properties:
        # Dossier contenant la configuration des ressources
        "directory":
          type: string
          required: true
        # Configuration des paramètres
        "parameters":
          type: object
          required: true
          properties:
            # Dossier contenant la configuration des paramètres
            "directory":
              type: string
              required: true
		# Configuration des ressources diffusées sur le service
		"resources":
			type: object
			required: true
			properties:
				# Dossiers contenant l'ensemble des fichiers de configuration des ressources.
				"directories":
					type: array
					required: true
          minItems: 1
          items:
            type: string
		# Configuration du network
		"network":
			type: object
			required: false
			properties:
				# Host
				"host":
					type: string
					required: false
				# Port
				"port":
					type: string
					required: false
    # Configuration des projections disponibles
    "projections":
      type: object
      required: true
      properties:
        # Dossier contenant les configurations
        "directory":
          type: string
          required: true
