openapi: "3.0.0"
info:
  description: "Description de l'API d'administration du service d'itinéraire."
  version: "1.0.0"
  title: "Administration du Service d'itinéraire"
  contact:
    email: "rdev@ign.fr"
servers:
  - url: "https://localhost:8080/admin/1.0.0/"
    description: "Serveur de test local"
tags:
- name: "Administration"
  description: "Administrer le service d'itinéraire"
paths:
  /version:
    get: 
      tags: 
      - "Administration"
      summary: "Obtenir la version du serveur."
      description: "Cette requête retourne la version du serveur. "
      operationId: "version"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  version:
                    type: "string"
  /health:
    get: 
      tags: 
      - "Administration"
      summary: "Obtenir l'état du serveur."
      description: "Cette requête retourne l'état du serveur. "
      operationId: "health"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  state:
                    type: "string"
  /server:
    get:
      tags:
      - "Administration"
      summary: "Obtenir la configuration du server."
      description: "Cette requête retourne la configuration du server. "
      operationId: "server"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  configFile:
                    type: "string"
                  configuration:
                    type: "object"
        403:
          description: "Not allowed"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
  /resource:
    get:
      tags:
      - "Administration"
      summary: "Obtenir la configuration d'une ressource."
      description: "Cette requête retourne la configuration d'une ressource."
      operationId: "get-resource"
      parameters:
      - name: "id"
        in: "query"
        description: "Tableau des ids de ressources à décrire. Chaque id peut être complet ou incomplet. S'il est complet, seule cette ressource sera décrite. Si aucune ressource ne correspond, alors toutes les ressources pouvant correspondre vont être décrite. Équivalent du LIKE en SQL."
        required: true
        schema:
          type: "array"
          items:
            type: "string"
        explode: false
        style: "pipeDelimited"
        example: "bduni"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
                  properties:
                    resourceId:
                      type: "string"
                    configFile:
                      type: "string"
                    configuration:
                      type: "object"
        400:
          description: "Invalid parameters"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        403:
          description: "Not allowed"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        404:
          description: "Not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
    post:
      tags:
      - "Administration"
      summary: "Modifier une ressource existante. Il faut fournir la configuration de la ressource à modifier."
      description: ""
      operationId: "post-resource"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createResource"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  configFile:
                    type: "string"
                  configuration:
                    type: "object"
        400:
          description: "Invalid parameters"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        403:
          description: "Not allowed"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        404:
          description: "Not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
    put:
      tags:
      - "Administration"
      summary: "Intégrer une nouvelle ressource. Il faut fournir la configuration de la ressource à intégrer."
      description: ""
      operationId: "put-resource"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createResource"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  configFile:
                    type: "string"
                  configuration:
                    type: "object"
        400:
          description: "Invalid parameters"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        403:
          description: "Not allowed"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        404:
          description: "Not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
    delete:
      tags:
      - "Administration"
      summary: "Intégrer une nouvelle ressource. Il faut fournir l'id des ressources à supprimer."
      description: ""
      operationId: "delete-resource"
      parameters:
      - name: "id"
        in: "query"
        description: "Tableau des ids de ressources à supprimer. Les ids doivent être complets."
        required: true
        schema:
          type: "array"
          items:
            type: "string"
        explode: false
        style: "pipeDelimited"
        example: "bduni"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
                  properties:
                    resourceId:
                      type: "string"
        400:
          description: "Invalid parameters"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        403:
          description: "Not allowed"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        404:
          description: "Not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
components:
  schemas:
    createResource:
      type: "object"
      properties:
        resource:
          type: "object"
          properties:
            file:
              type: "string"
    errorResponse:
      type: "object"
      properties:
        error:
          type: "object"
          properties:
            errorType:
              type: "string"
            message:
              type: "string"
