version: "3.7"

services:
  road2-centos:
    build:
      context: ..
      dockerfile: ./docker/centos-wo-aws/Dockerfile
      args:
        - dnsIP=${dns_ip}
        - dnsHost=${dns_host}
        - proxy=${proxy}
    image: road2-centos
    container_name: road2-centos-server
    depends_on:
      - pgrouting-procedures-centos
    environment:
      - NODE_ENV=debug
    ports:
      - 8080:8080
      - 9229:9229
      - 443:443
    volumes:
      - iti-data-volume:/home/docker/data
      - ${road2_src}:/home/docker/app/src
      - ${road2_test}:/home/docker/app/test
      - ${road2_config}:/home/docker/config
    networks:
      - iti-network
    secrets:
      - key
      - cert

  route-graph-generator-centos:
    build:
      context: ../../route-graph-generator/
      dockerfile: ./docker/centos7/Dockerfile
      args:
        - proxy=${proxy}
    image: route-graph-generator-centos
    container_name: route-graph-generator-centos
    depends_on:
      - pgrouting-procedures-centos
    volumes:
      - iti-data-volume:/home/docker/data
      - ${r2gg_src}:/usr/lib/python3.6/site-packages/r2gg/r2gg
    networks:
      - iti-network
    command: "./r2gg_pipeline.sh"
    environment:
      - R2GG_ARG=${R2GG_ARG}
      - GENERATION_TYPE=${GENERATION_TYPE}
    secrets:
      - db_config

  pgrouting-procedures-centos:
    build:
      context: ../../pgrouting-procedures/
      dockerfile: ./docker/centos7/Dockerfile
      args:
        - proxy=${proxy}
        - ipRange=${iprange}
    image: pgrouting-procedures-centos
    container_name: pgrouting-procedures-centos-server
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - iti-network
    volumes:
      - pgr-data-volume:/var/lib/pgsql
      - ${procedures_path}:/home/docker/pgrouting-procedures/sql

  road2-web-debian:
    build:
      context: ..
      dockerfile: ./docker/web/Dockerfile
      args:
        - dnsIP=${dns_ip}
        - dnsHost=${dns_host}
        - proxy=${proxy}
    image: road2-web-debian
    container_name: road2-web-debian-server
    depends_on:
      - road2-centos
    ports:
      - 8081:80
    volumes:
      - ${road2_web_src}:/home/docker/web/www/road2
    networks:
      - iti-network

  gatling-road2:
    image: denvazh/gatling
    container_name: gatling-road2-server
    depends_on:
      - road2-centos
    volumes:
      - ${gatling_user_files}:/opt/gatling/user-files
      - ${gatling_results}:/opt/gatling/results
    networks:
      - iti-network
    command: "-s ${gatling_test_name}"

volumes:
  iti-data-volume:
    name: iti-data-volume
  pgr-data-volume:
    name: pgr-data-volume

networks:
  iti-network:
    name: iti-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${iprange}

secrets:
  db_config:
    file: ${db_config_file}
  key:
    file: ${road2_key}
  cert:
    file: ${road2_cert}
